### ISSUE TITLE
TypeError: 'set' object is not subscriptable

### ISSUE THREAD

**Issue by jackL999** [AbigailBuccaneer/json2cmake#38]
Ubuntu 20.04.3 LTS
Python 3.8.10

json2cmake generates the following error

Traceback (most recent call last):
  File "/home/jk2/.local/bin/json2cmake", line 8, in <module>
    sys.exit(main())
  File "/home/jk2/.local/lib/python3.8/site-packages/json2cmake/__init__.py", line 223, in main
    database.write(args.outfile, name=args.name)
  File "/home/jk2/.local/lib/python3.8/site-packages/json2cmake/__init__.py", line 122, in write
    name = os.path.basename(os.path.commonprefix(files).rstrip("/_"))
  File "/usr/lib/python3.8/genericpath.py", line 76, in commonprefix
    if not isinstance(m[0], (list, tuple)):
TypeError: 'set' object is not subscriptable

**Comment by yifengyou** [comment]
edit /home/jk2/.local/lib/python3.8/site-packages/json2cmake/init.py

modify 

name = os.path.basename(os.path.commonprefix(list(files)).rstrip("/_"))

**Comment by owinebar** [comment]
Looks like the author has not been active since 2021, but I submitted a pull request with this modification anyway.

**Comment by robertlipe** [comment]
Awesome. Thank you. This fixes the same crash on MacOS, too.

It then bombed out on directories with spaces in names, but this is far, far from the first program with that issue. That's further than I'd _hoped_ to get extracting an ESP32 build from PlatformIO and trying to shove it into Cmake.
